services:

  app:
    build: .
    container_name: app
    env_file: .env
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      postgresql:
        condition: service_healthy
      alembic:
        condition: service_completed_successfully

  alembic:
    build: .
    container_name: alembic
    env_file: .env
    command: uv run alembic -c ./alembic.ini -x data=true upgrade head
    depends_on:
      postgresql:
        condition: service_healthy

  postgresql:
    image: postgres:15-alpine3.20
    container_name: postgresql
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 10s
      timeout: 3s
      retries: 3

volumes:
  postgres_data: