"""remove sub_token from users

Revision ID: 1a16a17e8f55
Revises: 1f87f83e7202
Create Date: 2026-05-01 19:46:17.762067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a16a17e8f55'
down_revision: Union[str, Sequence[str], None] = '1f87f83e7202'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub_token'), table_name='users')
    op.drop_column('users', 'sub_token')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_sub_token'), 'users', ['sub_token'], unique=True)
    # ### end Alembic commands ###
