"""add sub_token to users

Revision ID: 1f87f83e7202
Revises: 728db1cb29a0
Create Date: 2026-05-01 17:34:24.215137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f87f83e7202'
down_revision: Union[str, Sequence[str], None] = '728db1cb29a0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sub_token', sa.String(), nullable=True))
    op.create_index(op.f('ix_users_sub_token'), 'users', ['sub_token'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_sub_token'), table_name='users')
    op.drop_column('users', 'sub_token')
    # ### end Alembic commands ###
